[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common-base"
description = "minimal dependency for crates to now depend on whole common"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
tracing = "0.1"
directories-next = "2.0"

# Profiling / Tracy
# NOTE: This must be kept in sync with the `tracy-client` version used by the
# `tracing-tracy` version in `common/frontend`.
# Using `=` here keeps `cargo update` from breaking this.

[lib]
test = false
doctest = false
bench = false
