[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-voxygen-anim"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"
[features]
use-dyn-lib = ["lazy_static", "common-dynlib"]
be-dyn-lib = []
simd = ["vek/platform_intrinsics"]
plugins = [ "dep:common-state", "common-state/plugins"]

default = ["simd"]

[dependencies]
common = {package = "veloren-common", path = "../common"}
common-state = {package = "veloren-common-state", path = "../common/state", optional = true}
bytemuck = { version = "1.4", features=["derive"] }
vek = { version = "0.17.0", features = ["serde", "mint"] }
common-dynlib = {package = "veloren-common-dynlib", path = "../common/dynlib", optional = true}
inline_tweak = { version = "1.0.8", features = ["derive"] }

# Hot Reloading
lazy_static = { version = "1.4.0", optional = true }

[lib]
test = false
doctest = false
bench = false
