[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-voxygen-anim"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"


[dependencies]
common = {package = "veloren-common", path = "../common"}
bytemuck = { version = "1.4", features=["derive"] }
vek = { version = "0.17.0", features = ["serde", "mint"] }
inline_tweak = { version = "1.0.8", features = ["derive"] }

# Hot Reloading

[lib]
test = false
doctest = false
bench = false
