[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-voxygen-i18n-helpers"
description = "Crate for internalization and diagnostic of existing localizations."
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"
[dependencies]
common-net = {package = "veloren-common-net", path = "../../common/net"}
common = {package = "veloren-common", path = "../../common"}
i18n = {package = "veloren-client-i18n", path = "../client-i18n"}
# Utility
tracing = "0.1"



[lib]
test = false
doctest = false
bench = false
