[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-voxygen-egui"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"
[features]
use-dyn-lib = ["common-dynlib"]
be-dyn-lib = []

[dependencies]
client = {package = "veloren-client", path = "../../client"}
common = {package = "veloren-common", path = "../../common"}
egui = "0.36"
egui_plot = "0.37"
egui-winit = "0.36"
lazy_static = "1.4.0"
winit = "0.30"
common-dynlib = {package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true}
