[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-network-protocol"
description = "pure Protocol without any I/O itself"
version = "0.6.1"
edition = "2024"
license = "GPL-3.0-or-later"
[features]
metrics = ["prometheus"]
trace_pedantic = [] # use for debug only

default = ["metrics"]

[dependencies]

#tracing and metrics
tracing = "0.1"
prometheus = { version = "0.14", default-features = false, optional = true }
#stream flags
bitflags = "2.2.1"
rand = { version = "0.10", features = ["alloc"] }
# async traits
async-trait = "0.1.42"
bytes = "^1"
hashbrown = { version = "0.17", default-features = false, features = ["rayon", "serde", "nightly", "default-hasher", "inline-more", "equivalent"] }




[lib]
test = false
doctest = false
bench = false
