[package]
name = "voxy"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[package.metadata.trueos-blueprint]
profile = "release"
replicatable = false

[package.metadata.trueos-blueprint.build-env-paths]
CARGO_WORKSPACE_DIR = ".."

[features]
trueos-blueprint = ["voxygen/headless", "voxygen/picasso-assets", "noaudio"]
noaudio = ["voxygen/noaudio"]
default = ["trueos-blueprint"]

[dependencies]
voxygen = { package = "veloren-voxygen", path = "..", default-features = false }
trueos = { path = "../../TRUEOS-Blueprints/api", features = ["tokio-net-probe", "ui4-scene"] }

[[bin]]
name = "voxy"
path = "main.rs"

[profile.dev]
opt-level = 0
debug = 0
strip = "symbols"

[profile.release]
opt-level = 2
debug = 0
strip = "symbols"

# Cargo only applies patches from the root manifest of a build.
[patch.crates-io]
rusttype = { path = "../vendor/rusttype-0.8.3" }
wgpu = { path = "../../wgpu/wgpu" }
tynm = { path = "../vendor/tynm-0.1.10" }
wavefront = { path = "../vendor/wavefront-0.2.3" }
lz-fear = { path = "../vendor/lz-fear-0.2.0" }
png = { path = "../vendor/png-0.18.1" }
hashbrown_015 = { package = "hashbrown", path = "../vendor/hashbrown-0.15.5" }
rust-argon2 = { path = "../vendor/rust-argon2-2.1.0" }
specs = { path = "../vendor/specs" }
shred = { path = "../vendor/shred" }
hibitset = { path = "../vendor/hibitset" }
hashbrown = { path = "../vendor/hashbrown" }
indexmap = { path = "../vendor/indexmap" }
