[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common-systems"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"


[dependencies]
common = { package = "veloren-common", path = ".." }
common-net = { package = "veloren-common-net", path = "../net" }
common-ecs = { package = "veloren-common-ecs", path = "../ecs" }
common-base = { package = "veloren-common-base", path = "../base" }

rand = { version = "0.10", features = ["alloc"] }
tokio-parallel = { package = "veloren-tokio-parallel", path = "../tokio-parallel" }
tracing = "0.1"
vek = { version = "0.17.0", features = ["serde", "mint"] }
ordered-float = { version = "5", default-features = true }
itertools = "0.14"

# ECS
specs = { version = "0.20", features = ["nightly", "serde", "storage-event-control", "derive"] }

# Tweak running code



[lib]
test = false
doctest = false
bench = false
