[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common-frontend"
description = "common stuff that is used by server-cli and voxygen directly"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
common-base = { package = "veloren-common-base", path = "../base" }

# Logging
termcolor = "1.1"
tracing = "0.1"
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["ansi", "env-filter", "fmt", "smallvec", "time", "tracing-log"] }

# Tracy
# NOTE: This must be kept in sync with the `profiling` version in `common/base`.
# NOTE: `=` since the minor version of tracing-tracy bumped a major version of `tracy-client`

[lib]
test = false
doctest = false
bench = false
