[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"
[features]
no-assets = []
picasso-assets = ["common-assets/picasso-assets"]
bin_csv = ["csv", "clap"]
bin_graphviz = ["petgraph", "clap"]
bin_asset_migrate = []
rrt_pathfinding = ["kiddo"]
calendar_events = []


[dependencies]

common-base = { package = "veloren-common-base", path = "base" }
common-i18n = { package = "veloren-common-i18n", path = "i18n" }

# Serde
serde = { version = "1.0.118", features = ["derive", "rc"] }

# Util
enum-map = { version = "2.4", features = ["serde"] }
enumset = "1.1.3"
vek = { version = "0.17.0", features = ["serde", "mint"] }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std", "serde"] }
chrono-tz = { version = "0.10", features = ["serde"] }
itertools = "0.14"
serde_json = "1.0.50"
sha2 = "0.11"
ahash = "0.8"
inline_tweak = "1.0.8"

# Strum
strum = { version = "0.28", features = ["derive"] }

approx = "0.5.1"
crossbeam-utils = "0.8.7"
bitflags = { version = "2.2.1", features = ["serde"] }
lazy_static = "1.4.0"
num-derive = "0.4.0"
num-traits = "0.2"
ordered-float = { version = "5", default-features = true }
tokio-parallel = { package = "veloren-tokio-parallel", path = "tokio-parallel" }
ron = { version = "0.12", default-features = false, features = ["std"] }
roots = "0.0.8"
spin_sleep = "1.0"
tracing = "0.1"
uuid = { version = "1.4.1", default-features = false, features = [
    "serde",
    "v4",
] }
rand = { version = "0.10", features = ["alloc"] }
fxhash = "0.2.1"

# Assets
common-assets = { package = "veloren-common-assets", path = "assets" }
dot_vox = "5.1"
serde_repr = "0.1.6"

# csv export
csv = { version = "1.1.3", optional = true }
# graphviz exporters
petgraph = { version = "0.8.1", optional = true }
# K-d trees used for RRT pathfinding
kiddo = { version = "5", optional = true }
clap = { version = "4.2", features = ["derive", "env"], optional = true }

# Data structures
hashbrown = { version = "0.17", default-features = false, features = ["rayon", "serde", "nightly", "default-hasher", "inline-more", "equivalent"] }
slab = "0.4.2"
slotmap = { version = "1.0", features = ["serde"] }
indexmap = { version = "=2.14.2", features = ["rayon"] }

# ECS
specs = { version = "0.20", features = ["nightly", "serde", "storage-event-control", "shred-derive"] }


[build-dependencies]
regex = "1"












[lib]
test = false
doctest = false
bench = false

[target.'cfg(not(target_os = "trueos"))'.dependencies]
thread-priority = "3.0.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos"))'] }
