[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common-ecs"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]

tracing = "0.1"
common-base = { package = "veloren-common-base", path = "../base" }

# ECS
specs = { version = "0.20", features = ["nightly", "serde", "storage-event-control"] }



[lib]
test = false
doctest = false
bench = false
