[package]
autobins = false
autoexamples = false
autobenches = false
autotests = false
name = "veloren-common-dynlib"
version = "0.18.0"
edition = "2024"
license = "GPL-3.0-or-later"
[dependencies]
find_folder = {version = "0.3.0"}
libloading = {version = "0.9"}
notify = {version = "8.0.0"}
tracing = "0.1"
